const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Behaviors.Tween,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.Timer,
		C3.Behaviors.bound,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.scrollto,
		C3.Plugins.Touch,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Cryptography,
		C3.Plugins.BinaryData,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.Dictionary,
		C3.Plugins.Mouse,
		C3.Plugins.filechooser,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.Pathfinding.Cnds.OnArrived,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Pathfinding.Acts.AddObstacle,
		C3.Behaviors.Pathfinding.Acts.RegenerateMap,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Pathfinding.Cnds.IsMoving,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Pin.Acts.PinByDistance,
		C3.Behaviors.Pin.Acts.SetPinDistance,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Json.Exps.Get,
		C3.Behaviors.Pathfinding.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Pathfinding.Acts.Stop,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Behaviors.Bullet.Cnds.IsEnabled,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Text.Acts.SubInstanceVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.JavaScriptInEvents.Uisetup_Event6_Act1,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Text.Cnds.PickParent,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.JavaScriptInEvents.Uisetup_Event33_Act2,
		C3.JavaScriptInEvents.Uisetup_Event33_Act4,
		C3.JavaScriptInEvents.Uisetup_Event34_Act1,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.Json.Acts.AddTo,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Json.Acts.SetInstanceVar,
		C3.Plugins.Json.Acts.SetBoolInstanceVar,
		C3.Plugins.Json.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Json.Acts.SetJSON,
		C3.Plugins.Json.Acts.AddInstanceVar,
		C3.Plugins.Json.Cnds.CompareInstanceVar,
		C3.Plugins.BinaryData.Acts.SetFromText,
		C3.Plugins.Cryptography.Acts.EncryptBinary,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Cryptography.Cnds.OnEncryptionFinished,
		C3.Plugins.Browser.Acts.InvokeDownloadString,
		C3.Plugins.BinaryData.Exps.GetBase64,
		C3.Plugins.filechooser.Acts.Click,
		C3.Plugins.filechooser.Cnds.OnChanged,
		C3.Plugins.filechooser.Exps.FileCount,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.filechooser.Exps.FileURLAt,
		C3.Plugins.BinaryData.Acts.SetFromBase64,
		C3.Plugins.Cryptography.Acts.DecryptBinary,
		C3.Plugins.Cryptography.Cnds.OnDecryptionFinished,
		C3.Plugins.BinaryData.Exps.GetAllText,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.Plugins.Json.Acts.Destroy,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Json.Exps.GetAsCompactString,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Exps.layoutscale,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Exps.layoutname,
		C3.JavaScriptInEvents.Ads_Event1_Act1,
		C3.JavaScriptInEvents.Ads_Event2_Act2,
		C3.JavaScriptInEvents.Ads_Event2_Act3,
		C3.JavaScriptInEvents.Ads_Event3_Act1,
		C3.JavaScriptInEvents.Ads_Event3_Act2,
		C3.JavaScriptInEvents.Ads_Event3_Act3,
		C3.Plugins.Text.Exps.LayerNumber,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.JavaScriptInEvents.Ads_Event22_Act1,
		C3.JavaScriptInEvents.Ads_Event23_Act1,
		C3.Plugins.LocalStorage.Exps.MemoryStorageAsJSON
	];
};
self.C3_JsPropNameTable = [
	{Anchor: 0},
	{Tween: 0},
	{joystick: 0},
	{DragDrop: 0},
	{Pin: 0},
	{joystick_collider: 0},
	{joystick_stick: 0},
	{WalletAmount: 0},
	{WalletUI: 0},
	{widthSize: 0},
	{heightSize: 0},
	{current: 0},
	{Notification: 0},
	{NotificationText: 0},
	{MenuButton: 0},
	{BlackBg: 0},
	{AmountTxt: 0},
	{AmountAdded: 0},
	{Characters: 0},
	{CharacterTxt: 0},
	{ClosePopUp: 0},
	{MaxTxt: 0},
	{PopupHeader: 0},
	{PopupTitle: 0},
	{ReqHeader: 0},
	{ReqHeaderTxt: 0},
	{name: 0},
	{SoundAndMusic: 0},
	{value: 0},
	{Amount: 0},
	{AmountBg: 0},
	{CashLogo: 0},
	{frameNumber: 0},
	{PopupBg: 0},
	{Rotate: 0},
	{ShineEffect: 0},
	{ShopHeader: 0},
	{UIPos: 0},
	{stamina: 0},
	{stack: 0},
	{speed: 0},
	{lock: 0},
	{UpgradeBg: 0},
	{UpgradeButton: 0},
	{UpgradeTxt: 0},
	{CashAmountTxt: 0},
	{UpgradeAmountTxt: 0},
	{type: 0},
	{ReqHeader2: 0},
	{BebirthInfo: 0},
	{price: 0},
	{rebirthBtn: 0},
	{RebirthPrice: 0},
	{rebirthCard: 0},
	{rebirthCountTxt: 0},
	{CharacterTxt2: 0},
	{Sine: 0},
	{PlayerItemHold: 0},
	{capacity: 0},
	{pick: 0},
	{drop: 0},
	{overlappingSleep: 0},
	{Bullet: 0},
	{Timer: 0},
	{BoundToLayout: 0},
	{Player: 0},
	{customerType: 0},
	{cartORNot: 0},
	{itemCount: 0},
	{stall: 0},
	{step: 0},
	{prevX: 0},
	{maxCapacity: 0},
	{stop: 0},
	{counter: 0},
	{counterPos: 0},
	{exit: 0},
	{cartCapacity: 0},
	{stop2: 0},
	{counterArrived: 0},
	{onCounter: 0},
	{Pathfinding: 0},
	{Customer: 0},
	{Cashier: 0},
	{isStop: 0},
	{frame: 0},
	{text: 0},
	{ispicked: 0},
	{hide: 0},
	{running: 0},
	{start: 0},
	{rest: 0},
	{reqCapcity: 0},
	{looking: 0},
	{chooseStall: 0},
	{restPosX: 0},
	{restPoxY: 0},
	{dustbin: 0},
	{Staff: 0},
	{ScrollTo: 0},
	{camera: 0},
	{Touch: 0},
	{AJAX: 0},
	{JSON: 0},
	{Keyboard: 0},
	{Audio: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{DataLoad: 0},
	{DataCount: 0},
	{Saving: 0},
	{DataSave: 0},
	{Cryptography: 0},
	{BinaryData: 0},
	{imagePoint: 0},
	{picked: 0},
	{Barricade: 0},
	{Basket: 0},
	{EntryGate: 0},
	{Tree: 0},
	{Sprite: 0},
	{move: 0},
	{Crab: 0},
	{Arrow: 0},
	{PlacePrice: 0},
	{PlacePriceBg: 0},
	{index: 0},
	{iso: 0},
	{bird: 0},
	{rowCount: 0},
	{front: 0},
	{Yoffset: 0},
	{Cash: 0},
	{Banana: 0},
	{contain: 0},
	{BananaDropPoint: 0},
	{bananaCount: 0},
	{BananaPlant: 0},
	{BananaYogurtDropPoint: 0},
	{CornGround: 0},
	{create: 0},
	{pickedItem: 0},
	{CornPlant: 0},
	{CornDropPoint: 0},
	{eating: 0},
	{sleep: 0},
	{Chicken: 0},
	{ChickenCornDropPoint: 0},
	{EggCornDropPoint: 0},
	{EggDropPoint: 0},
	{Nest: 0},
	{CornCowDropPoint: 0},
	{Cow: 0},
	{MilkCornDropPoint: 0},
	{MilkDropPoint: 0},
	{MilkTray: 0},
	{CornPopcornDropPoint: 0},
	{PopcornCornDropPoint: 0},
	{PopcornDropPoint: 0},
	{making: 0},
	{PopcornMachine: 0},
	{YogurtDropPoint: 0},
	{YougurtBananaDropPoint: 0},
	{machineWidth: 0},
	{machineHeight: 0},
	{YougurtMachine: 0},
	{Bowl: 0},
	{caution: 0},
	{Sine2: 0},
	{Clock: 0},
	{CornEatBox: 0},
	{MachineFix: 0},
	{MachineFixTool: 0},
	{MachineItemTray: 0},
	{MachineProblemIcon: 0},
	{MachineSensor: 0},
	{Solid: 0},
	{MachineTable: 0},
	{SleepReaction: 0},
	{smoke: 0},
	{DropPoint: 0},
	{Dustbin: 0},
	{Ground: 0},
	{isOverlapping: 0},
	{Counter: 0},
	{PlaceGround: 0},
	{SpawnPoint: 0},
	{customer: 0},
	{customerPos: 0},
	{Stalls: 0},
	{BananaGround: 0},
	{mirrored: 0},
	{sort: 0},
	{sale: 0},
	{check: 0},
	{pickedByCustomer: 0},
	{Items: 0},
	{IsometricSensor: 0},
	{Items2: 0},
	{Bird: 0},
	{BirdShadow: 0},
	{birdTimer: 0},
	{CounterSensor: 0},
	{hand: 0},
	{CustomerItemHold: 0},
	{customerPosition: 0},
	{DragAndDrop: 0},
	{enviromentItems: 0},
	{Mask: 0},
	{moneyIndex: 0},
	{StaffHoldItems: 0},
	{Sprite2: 0},
	{topobject: 0},
	{cc: 0},
	{Logo: 0},
	{Dictionary: 0},
	{customSolid: 0},
	{Mouse: 0},
	{rebirthicon: 0},
	{uiIconRebrith: 0},
	{FileChooser: 0},
	{Download_btn: 0},
	{Upload_btn: 0},
	{IsometricsItems: 0},
	{CookItems: 0},
	{Stop: 0},
	{sonorsf: 0},
	{birdReward: 0},
	{startBirdTimer: 0},
	{cashierAnimationSpeed: 0},
	{cashierStarted: 0},
	{stallCount: 0},
	{counterOffset: 0},
	{CreateMoney: 0},
	{startCashX: 0},
	{addAmount: 0},
	{startCashY: 0},
	{startCashX2: 0},
	{columnCount: 0},
	{startCashY2: 0},
	{YOffset: 0},
	{cashCount: 0},
	{customeStart: 0},
	{customerNumber: 0},
	{createGapTime: 0},
	{xSpace: 0},
	{ySpace: 0},
	{number: 0},
	{playerAnimation: 0},
	{assitantSpeed: 0},
	{resPosX: 0},
	{resPosY: 0},
	{crabSpeed: 0},
	{waitDrop: 0},
	{offset: 0},
	{cornWait: 0},
	{bananaWait: 0},
	{width: 0},
	{height: 0},
	{currentUnlock: 0},
	{currentPrice: 0},
	{inScreen: 0},
	{showing: 0},
	{pickNotification: 0},
	{lookForNotification: 0},
	{popUp: 0},
	{animationOffset: 0},
	{addValue: 0},
	{dragAndDropY: 0},
	{nameFrame: 0},
	{sntxt: 0},
	{Year: 0},
	{chickenStamina: 0},
	{chickenStack: 0},
	{chickenSpeed: 0},
	{playerCapacity: 0},
	{maxlevel: 0},
	{wallet: 0},
	{Zoom: 0},
	{Progress: 0},
	{RebirthLvl: 0},
	{sound: 0},
	{music: 0},
	{soundName: 0},
	{Volume: 0},
	{adActive: 0},
	{adsInit: 0},
	{AdFollow: 0},
	{Pause: 0},
	{IniTimeScale: 0},
	{LayerCount: 0}
];

self.InstanceType = {
	joystick: class extends self.ISpriteInstance {},
	joystick_collider: class extends self.ISpriteInstance {},
	joystick_stick: class extends self.ISpriteInstance {},
	WalletAmount: class extends self.ITextInstance {},
	WalletUI: class extends self.ISpriteInstance {},
	Notification: class extends self.ISpriteInstance {},
	NotificationText: class extends self.ITextInstance {},
	MenuButton: class extends self.ISpriteInstance {},
	BlackBg: class extends self.ISpriteInstance {},
	AmountTxt: class extends self.ITextInstance {},
	AmountAdded: class extends self.ITextInstance {},
	Characters: class extends self.ISpriteInstance {},
	CharacterTxt: class extends self.ITextInstance {},
	ClosePopUp: class extends self.ISpriteInstance {},
	MaxTxt: class extends self.ITextInstance {},
	PopupHeader: class extends self.ISpriteInstance {},
	PopupTitle: class extends self.ISpriteInstance {},
	ReqHeader: class extends self.ISpriteInstance {},
	ReqHeaderTxt: class extends self.ITextInstance {},
	SoundAndMusic: class extends self.ISpriteInstance {},
	AmountBg: class extends self.ISpriteInstance {},
	CashLogo: class extends self.ISpriteInstance {},
	PopupBg: class extends self.ISpriteInstance {},
	ShineEffect: class extends self.ISpriteInstance {},
	ShopHeader: class extends self.ISpriteInstance {},
	UIPos: class extends self.ISpriteInstance {},
	UpgradeBg: class extends self.ISpriteInstance {},
	UpgradeButton: class extends self.ISpriteInstance {},
	UpgradeTxt: class extends self.ITextInstance {},
	CashAmountTxt: class extends self.ITextInstance {},
	UpgradeAmountTxt: class extends self.ITextInstance {},
	ReqHeader2: class extends self.ISpriteInstance {},
	BebirthInfo: class extends self.ITextInstance {},
	rebirthBtn: class extends self.ISpriteInstance {},
	RebirthPrice: class extends self.ITextInstance {},
	rebirthCard: class extends self.ISpriteInstance {},
	rebirthCountTxt: class extends self.ITextInstance {},
	CharacterTxt2: class extends self.ITextInstance {},
	PlayerItemHold: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Customer: class extends self.ISpriteInstance {},
	Cashier: class extends self.ISpriteInstance {},
	Staff: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	DataLoad: class extends self.IJSONInstance {},
	DataSave: class extends self.IJSONInstance {},
	Cryptography: class extends self.IInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	Barricade: class extends self.ISpriteInstance {},
	Basket: class extends self.ISpriteInstance {},
	EntryGate: class extends self.ISpriteInstance {},
	Tree: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Crab: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	PlacePrice: class extends self.ITextInstance {},
	PlacePriceBg: class extends self.ISpriteInstance {},
	Cash: class extends self.ISpriteInstance {},
	Banana: class extends self.ISpriteInstance {},
	BananaDropPoint: class extends self.ISpriteInstance {},
	BananaPlant: class extends self.ISpriteInstance {},
	BananaYogurtDropPoint: class extends self.ISpriteInstance {},
	CornGround: class extends self.ISpriteInstance {},
	CornPlant: class extends self.ISpriteInstance {},
	CornDropPoint: class extends self.ISpriteInstance {},
	Chicken: class extends self.ISpriteInstance {},
	ChickenCornDropPoint: class extends self.ISpriteInstance {},
	EggCornDropPoint: class extends self.ISpriteInstance {},
	EggDropPoint: class extends self.ISpriteInstance {},
	Nest: class extends self.ISpriteInstance {},
	CornCowDropPoint: class extends self.ISpriteInstance {},
	Cow: class extends self.ISpriteInstance {},
	MilkCornDropPoint: class extends self.ISpriteInstance {},
	MilkDropPoint: class extends self.ISpriteInstance {},
	MilkTray: class extends self.ISpriteInstance {},
	CornPopcornDropPoint: class extends self.ISpriteInstance {},
	PopcornCornDropPoint: class extends self.ISpriteInstance {},
	PopcornDropPoint: class extends self.ISpriteInstance {},
	PopcornMachine: class extends self.ISpriteInstance {},
	YogurtDropPoint: class extends self.ISpriteInstance {},
	YougurtBananaDropPoint: class extends self.ISpriteInstance {},
	YougurtMachine: class extends self.ISpriteInstance {},
	Bowl: class extends self.ISpriteInstance {},
	caution: class extends self.ISpriteInstance {},
	Clock: class extends self.ISpriteInstance {},
	CornEatBox: class extends self.ISpriteInstance {},
	MachineFix: class extends self.ISpriteInstance {},
	MachineFixTool: class extends self.ISpriteInstance {},
	MachineItemTray: class extends self.ISpriteInstance {},
	MachineProblemIcon: class extends self.ISpriteInstance {},
	MachineSensor: class extends self.ISpriteInstance {},
	MachineTable: class extends self.ISpriteInstance {},
	SleepReaction: class extends self.ISpriteInstance {},
	smoke: class extends self.ISpriteInstance {},
	DropPoint: class extends self.ISpriteInstance {},
	Dustbin: class extends self.ISpriteInstance {},
	Ground: class extends self.ITiledBackgroundInstance {},
	Counter: class extends self.ISpriteInstance {},
	PlaceGround: class extends self.ISpriteInstance {},
	SpawnPoint: class extends self.ISpriteInstance {},
	Stalls: class extends self.ISpriteInstance {},
	BananaGround: class extends self.ISpriteInstance {},
	Items: class extends self.ISpriteInstance {},
	IsometricSensor: class extends self.ISpriteInstance {},
	Items2: class extends self.ISpriteInstance {},
	Bird: class extends self.ISpriteInstance {},
	BirdShadow: class extends self.ISpriteInstance {},
	birdTimer: class extends self.ISpriteInstance {},
	CounterSensor: class extends self.ISpriteInstance {},
	CustomerItemHold: class extends self.ISpriteInstance {},
	customerPosition: class extends self.ISpriteInstance {},
	DragAndDrop: class extends self.ISpriteInstance {},
	enviromentItems: class extends self.ISpriteInstance {},
	Mask: class extends self.ISpriteInstance {},
	moneyIndex: class extends self.ISpriteInstance {},
	StaffHoldItems: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	topobject: class extends self.ITextInstance {},
	cc: class extends self.ITextInstance {},
	Logo: class extends self.ISpriteInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	customSolid: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	rebirthicon: class extends self.ISpriteInstance {},
	uiIconRebrith: class extends self.ISpriteInstance {},
	FileChooser: class extends self.IFileChooserInstance {},
	Download_btn: class extends self.ISpriteInstance {},
	Upload_btn: class extends self.ISpriteInstance {},
	IsometricsItems: class extends self.ISpriteInstance {},
	CookItems: class extends self.ISpriteInstance {},
	Stop: class extends self.ISpriteInstance {},
	sonorsf: class extends self.ISpriteInstance {}
}