{
	"version": 1714930033,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/madotsuki-sheet0.png",
		"images/tiledbackground.png",
		"images/wall-sheet0.png",
		"images/poniko-sheet0.png",
		"images/monoko-sheet0.png",
		"images/monoe-sheet0.png",
		"images/spritefont.png",
		"images/9patch.png",
		"images/inspect-sheet0.png",
		"images/bun-sheet0.png",
		"images/bun-sheet1.png",
		"images/handdialogue-sheet0.png",
		"images/spritefontname.png",
		"images/face-sheet0.png",
		"images/face-sheet1.png",
		"images/face-sheet2.png",
		"images/deltarune-sheet0.png",
		"images/doorteleport-sheet0.png",
		"images/fade-sheet0.png",
		"images/urosmonk-sheet0.png",
		"images/sans-sheet0.png",
		"images/battleui-sheet0.png",
		"images/amongus-sheet0.png",
		"images/sselected-sheet0.png",
		"images/gridbattle.png",
		"images/soul-sheet0.png",
		"images/stressed-sheet0.png",
		"images/bullet-sheet0.png",
		"images/blackspace-sheet0.png",
		"images/damagefont.png",
		"images/health-sheet0.png",
		"images/badhealth-sheet0.png",
		"images/ballin-sheet0.png",
		"images/ballin-sheet1.png",
		"images/spritefontwin.png",
		"images/flag-sheet0.png",
		"images/spritefonthealth.png",
		"images/moveplease-sheet0.png",
		"images/melon-sheet0.png",
		"images/melon-sheet1.png",
		"images/bush-sheet0.png",
		"images/bush-sheet1.png",
		"images/tilemap.png",
		"images/ponihouse-sheet0.png",
		"images/ponihouse-sheet1.png",
		"images/fishingguy-sheet0.png",
		"images/fishingguy-sheet1.png",
		"images/pirori-sheet0.png",
		"images/pirori-sheet1.png",
		"images/pirori-sheet2.png",
		"images/merutomaro-sheet0.png",
		"images/walkingeye-sheet0.png",
		"images/walkingeye-sheet1.png",
		"images/cutanimation-sheet0.png",
		"images/deadboi-sheet0.png",
		"images/deadboi-sheet1.png",
		"images/sseasnake-sheet0.png",
		"images/dropfish-sheet0.png",
		"images/bricks-sheet0.png",
		"images/bricks-sheet1.png",
		"images/bricks-sheet2.png",
		"images/mewo-sheet0.png",
		"images/mewo-sheet1.png",
		"images/mewo-sheet2.png",
		"images/headspacetiledbackground.png",
		"images/funnydrawings-sheet0.png",
		"images/funnydrawings-sheet1.png",
		"images/funnydrawings-sheet2.png",
		"images/balloon-sheet0.png",
		"images/painblob-sheet0.png",
		"images/painblob-sheet1.png",
		"images/painblob-sheet2.png",
		"images/angrypainblob-sheet0.png",
		"images/angrypainblob-sheet1.png",
		"images/gamefaces-sheet0.png",
		"images/gamefaces-sheet1.png",
		"images/coolerbackgrounds-sheet0.png",
		"images/coolerbackgrounds-sheet1.png",
		"images/coolerbackgrounds-sheet2.png",
		"images/photograph-sheet0.png",
		"images/photograph-sheet1.png",
		"images/omoriboy-sheet0.png",
		"images/dialoguejumpscare-sheet0.png",
		"images/picknicblancket-sheet0.png",
		"images/urotsuki-sheet0.png",
		"images/greencircle-sheet0.png",
		"images/nexusdoors-sheet0.png",
		"images/cranberryspritefont.png",
		"images/sign-sheet0.png",
		"images/witchwall-sheet0.png",
		"images/lightswitch-sheet0.png",
		"images/kyuukyuukun-sheet0.png",
		"images/spiroataiondestroyufo-sheet0.png",
		"images/armattack-sheet0.png",
		"images/tiledbackgroundwet.png",
		"images/ky-sheet0.png",
		"images/ky-sheet1.png",
		"images/floorpizza-sheet0.png",
		"images/floorpizza-sheet1.png",
		"images/vomit_chan_my_beloved-sheet0.png",
		"images/destroydoors-sheet0.png",
		"images/tiledbackgroundsnowhalation.png",
		"images/particlessnow.png",
		"images/mafurako-sheet0.png",
		"images/rraincloud-sheet0.png",
		"images/fireswitch-sheet0.png",
		"images/fireswitch-sheet1.png",
		"images/fireswitch-sheet2.png",
		"images/puzzledoorup-sheet0.png",
		"images/puzzledoorup-sheet1.png",
		"images/puzzledoordown-sheet0.png",
		"images/angryfrog-sheet0.png",
		"images/frog-sheet0.png",
		"images/frog-sheet1.png",
		"images/frog-sheet2.png",
		"images/eggof-sheet0.png",
		"images/flybullet-sheet0.png",
		"images/snoman-sheet0.png",
		"images/snoman-sheet1.png",
		"images/puddle-sheet0.png",
		"images/youmonster-sheet0.png",
		"images/kamakurako-sheet0.png",
		"images/kamakurako-sheet1.png",
		"images/igloo-sheet0.png",
		"images/invisscarf-sheet0.png",
		"images/smolyuki-sheet0.png",
		"images/smolyuki-sheet1.png",
		"images/smoloni-sheet0.png",
		"images/smoloni-sheet1.png",
		"images/yukionna-sheet0.png",
		"images/yukionna-sheet1.png",
		"images/fcdemon-sheet0.png",
		"images/fcdemon-sheet1.png",
		"images/fcdemon-sheet2.png",
		"images/electricity-sheet0.png",
		"images/electricity-sheet1.png",
		"images/snowballpipebomb-sheet0.png",
		"images/explosion-sheet0.png",
		"images/explosion-sheet1.png",
		"images/explosion-sheet2.png",
		"images/burger-sheet0.png",
		"images/somethingbackground-sheet0.png",
		"images/somethingbackground-sheet1.png",
		"images/headspacetiledbackground2.png",
		"images/monohouse-sheet0.png",
		"images/carpoet-sheet0.png",
		"images/rock-sheet0.png",
		"images/eyeperson-sheet0.png",
		"images/eyeperson-sheet1.png",
		"images/eyeperson-sheet2.png",
		"images/angryeye-sheet0.png",
		"images/angryeye-sheet1.png",
		"images/spinningmonoko-sheet0.png",
		"images/spinningmonoko-sheet1.png",
		"images/camera-sheet0.png",
		"images/breakrockanimation-sheet0.png",
		"images/eyecube-sheet0.png",
		"images/angrydave-sheet0.png",
		"images/angrydave-sheet1.png",
		"images/introcutscene-sheet0.png",
		"images/introcutscene-sheet1.png",
		"images/bedmado-sheet0.png",
		"images/bedomori-sheet0.png",
		"images/musicbox-sheet0.png",
		"images/picnicbasket-sheet0.png",
		"images/dave-sheet0.png",
		"images/dave-sheet1.png",
		"images/dave-sheet2.png",
		"images/bulletdave-sheet0.png",
		"images/bulletdave-sheet1.png",
		"images/sunsetcliff-sheet0.png",
		"images/sunsetcliff-sheet1.png",
		"images/eyebutton-sheet0.png",
		"images/something-sheet0.png",
		"images/animefight-sheet0.png",
		"images/omori-sheet0.png",
		"images/pizzaa-sheet0.png",
		"images/pizzaaa-sheet0.png",
		"images/pizzaaaa-sheet0.png",
		"images/helppizza-sheet0.png",
		"images/pizzaaaaa-sheet0.png",
		"images/helppizzahelp-sheet0.png",
		"images/pizzaaaaaa-sheet0.png",
		"images/exclamation-sheet0.png",
		"images/exclamation-sheet1.png",
		"images/questcomplete-sheet0.png",
		"images/warning-sheet0.png",
		"images/logoomori-sheet0.png",
		"images/logolight-sheet0.png",
		"images/logolight-sheet1.png",
		"images/logolight-sheet2.png",
		"images/logoyumenikki-sheet0.png",
		"images/logomado-sheet0.png",
		"images/logomado-sheet1.png",
		"images/logomado-sheet2.png",
		"images/logocreds-sheet0.png",
		"images/logobuttons-sheet0.png",
		"images/logohand-sheet0.png",
		"images/dooropen-sheet0.png",
		"images/thanksforplaying-sheet0.png",
		"images/door-sheet0.png",
		"images/tv-sheet0.png",
		"images/bookshelf-sheet0.png",
		"images/savingdesk-sheet0.png",
		"images/savingdesk-sheet1.png",
		"images/carpet-sheet0.png",
		"images/floorpillow-sheet0.png",
		"images/floorpillow-sheet1.png",
		"images/floorpillow-sheet2.png",
		"images/slidingdoor-sheet0.png",
		"images/bedponiko-sheet0.png",
		"images/bookshelfpink-sheet0.png",
		"images/bookshelfpink-sheet1.png",
		"images/windows-sheet0.png",
		"images/differentcarpet-sheet0.png",
		"images/randomstuff-sheet0.png",
		"images/pc-sheet0.png",
		"images/splant-sheet0.png",
		"images/bedmono-sheet0.png",
		"images/niko-sheet0.png",
		"images/jimbo-sheet0.png",
		"images/jimbo-sheet1.png",
		"images/cheespider-sheet0.png",
		"images/novaflow-sheet0.png",
		"images/novaflow-sheet1.png",
		"images/takofuusen-sheet0.png",
		"images/fire-sheet0.png",
		"images/fire-sheet1.png",
		"images/fire-sheet2.png",
		"images/tokutokun-sheet0.png",
		"images/tokutokun-sheet1.png",
		"images/pool-sheet0.png",
		"images/towel-sheet0.png",
		"images/towel-sheet1.png",
		"images/soap-sheet0.png",
		"images/frozenfrog-sheet0.png",
		"images/fumo-sheet0.png",
		"images/cirno-sheet0.png",
		"images/spellcard-sheet0.png",
		"images/decor-sheet0.png",
		"images/masada-sheet0.png",
		"images/glitch-sheet0.png",
		"images/angryram-sheet0.png",
		"images/ram-sheet0.png",
		"images/ram-sheet1.png",
		"images/bulletballbombob-sheet0.png",
		"images/bulletballbombob-sheet1.png",
		"images/thesun-sheet0.png",
		"images/thesun-sheet1.png",
		"images/thesun-sheet2.png",
		"images/alulaimposter-sheet0.png",
		"images/alulaimposter-sheet1.png",
		"images/alulaimposter-sheet2.png",
		"images/alulareal-sheet0.png",
		"images/entity-sheet0.png",
		"images/theworldmachine-sheet0.png",
		"images/theworldmachine-sheet1.png",
		"images/theworldmachine-sheet2.png",
		"images/z-sheet0.png",
		"images/particles.png",
		"images/questions-sheet0.png",
		"images/fluorette-sheet0.png",
		"images/itsomover-sheet0.png",
		"images/itsomover-sheet1.png",
		"images/discofloor-sheet0.png",
		"media/dog bark mario paint.ogg",
		"media/dialogue sound.ogg",
		"media/omori battle encounter sound effect [gboq_ut2m_8].ogg",
		"media/critical hit omori sfx [bu-8jqaouw8].ogg",
		"media/enemy spotted.ogg",
		"media/omori attack omori sfx [bhwxmfwen34].ogg",
		"media/mewo sound effect (omori) [kdn8pagaxs8].ogg",
		"media/effect pickup sound yume nikki.ogg",
		"media/snd_splat.ogg",
		"media/deltarune explosion greenscreen.ogg",
		"media/game over omori sfx [o_gjuj7u5sq].ogg",
		"media/picnic heal (full) omori sfx [mtm93ndkyig].ogg",
		"media/pot smash omori sfx [qvmlv_i1t7o].ogg",
		"media/quest complete omori sfx [0z4nknhmkae].ogg",
		"media/ayo the pizza here.ogg",
		"media/roblox pizza sound effect.ogg",
		"media/loop good morning - omori [3ppdn022idq].ogg",
		"media/start good morning - omori [3ppdn022idq].ogg",
		"media/menu select.ogg",
		"media/file loaded omori sfx [dywbzjs9tvk].ogg",
		"media/omori - opening cutscene [7e1zaf7owlg].ogg",
		"media/aztec rave monkey.ogg",
		"media/sound effect tada.ogg",
		"media/traffic light green.ogg",
		"media/traffic light red.ogg",
		"media/swish.ogg",
		"media/oneshot dialogue sound.ogg",
		"media/takofuusen.ogg",
		"media/thunder.ogg",
		"media/ding omori sfx [l3fjguj9teq].ogg",
		"media/glitch2 oneshot.ogg",
		"media/hero attack omori sfx [f-3_ge8nhgy].ogg",
		"media/laser_shoot61.ogg",
		"media/sheep1.ogg",
		"media/sheep2.ogg",
		"media/sheep3.ogg",
		"media/sheep4.ogg",
		"media/sheep5.ogg",
		"media/sheep6.ogg",
		"media/sheep7.ogg",
		"media/sheep_demon.ogg",
		"media/my epic song.ogg",
		"media/omori ost - 002 white space [ real ].ogg",
		"media/omori ost - 003 lost at a sleepover [hldull8apdw].ogg",
		"media/omori ost - 005 by your side. [7giwv__qx4m].ogg",
		"media/omori ost - 010 so, how'd we do [l1vuc1-9fh8].ogg",
		"media/omori ost - 015 tussle among trees [dwxivn9ewvy].ogg",
		"media/omori ost - 018 poems in the fog [lhaneymts0w].ogg",
		"media/omori ost - 030 snow forest - a single flower blooms [polg-0wwxje].ogg",
		"media/omori ost - 031 white surf style 6 [_7fgh_1cwt0].ogg",
		"media/omori_100 flute room.ogg",
		"media/omori ost -  072 those who forget history [y4jrowx8dcq].ogg",
		"media/omori ost - 086 world's end valentine [rlqd9qwkjlm].ogg",
		"media/omori ost - 116 underwater prom queens [7xl5kre19y4].ogg",
		"media/omori ost - 124 flouring with you [3ybe5w0gbto].ogg",
		"media/omori ost - 067 the heart of the desert [-fneopbzkv4].ogg",
		"media/omori ost - 001 title [9d9e6xmnn9q].ogg",
		"media/eleventhhour.ogg",
		"media/omori ost - 069 pranked. [ueph9oz0iku].ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}